import type { Question } from './types'

// 18 original-wording questions grouped into sections.
export const questions: Question[] = [
  {
    id: 'age',
    section: 'Demographics',
    title: 'What is your age?',
    type: 'single',
    options: [
      { value: 'under18', label: 'Under 18' },
      { value: '18to24', label: '18–24' },
      { value: '25to34', label: '25–34' },
      { value: '35to44', label: '35–44' },
      { value: '45to54', label: '45–54' },
      { value: '55plus', label: '55 and above' },
    ],
  },
  {
    id: 'gender',
    section: 'Demographics',
    title: 'What is your gender?',
    type: 'single',
    options: [
      { value: 'female', label: 'Female' },
      { value: 'male', label: 'Male' },
      { value: 'preferNotToSay', label: 'Prefer not to say' },
    ],
  },
  {
    id: 'waterType',
    section: 'Demographics',
    title: 'What type of water do you use for washing your hair?',
    type: 'single',
    options: [
      { value: 'soft', label: 'Soft water' },
      { value: 'hard', label: 'Hard water' },
      { value: 'RO', label: 'RO / filtered water' },
      { value: 'unsure', label: 'Not sure' },
    ],
  },
  {
    id: 'texture',
    section: 'Hair basics',
    title: 'What best describes your natural hair texture?',
    type: 'single',
    options: [
      { value: 'straight', label: 'Straight' },
      { value: 'wavy', label: 'Wavy' },
      { value: 'curly', label: 'Curly' },
      { value: 'coily', label: 'Coily' },
    ],
  },
  {
    id: 'thickness',
    section: 'Hair basics',
    title: 'How would you describe each individual strand?',
    type: 'single',
    options: [
      { value: 'fine', label: 'Fine' },
      { value: 'medium', label: 'Medium' },
      { value: 'thick', label: 'Thick' },
    ],
  },
  {
    id: 'density',
    section: 'Hair basics',
    title: 'How much hair sits on your scalp overall?',
    type: 'single',
    options: [
      { value: 'low', label: 'Low density' },
      { value: 'medium', label: 'Medium density' },
      { value: 'high', label: 'High density' },
      { value: 'unsure', label: 'Not sure' },
    ],
  },
  {
    id: 'scalp',
    section: 'Scalp',
    title: 'How does your scalp feel one day after washing?',
    type: 'single',
    options: [
      { value: 'dry', label: 'Dry or tight' },
      { value: 'balanced', label: 'Balanced' },
      { value: 'oily', label: 'Oily' },
      { value: 'veryOily', label: 'Very oily' },
    ],
  },
  {
    id: 'flakes',
    section: 'Scalp',
    title: 'How often do you notice visible flakes?',
    type: 'single',
    options: [
      { value: 'never', label: 'Never' },
      { value: 'occasionally', label: 'Occasionally' },
      { value: 'frequently', label: 'Frequently' },
      { value: 'almostAlways', label: 'Almost always' },
    ],
  },
  {
    id: 'hairFall',
    section: 'Concerns',
    title: 'How would you describe your current hair fall?',
    type: 'single',
    options: [
      { value: 'minimal', label: 'Minimal' },
      { value: 'mild', label: 'Mild' },
      { value: 'moderate', label: 'Moderate' },
      { value: 'significant', label: 'Significant' },
    ],
  },
  {
    id: 'thinning',
    section: 'Concerns',
    title: 'Has your hair been feeling thinner or less dense?',
    type: 'single',
    options: [
      { value: 'notAtAll', label: 'Not at all' },
      { value: 'slightly', label: 'Slightly' },
      { value: 'moderately', label: 'Moderately' },
      { value: 'significantly', label: 'Significantly' },
    ],
  },
  {
    id: 'frizz',
    section: 'Concerns',
    title: 'How much does frizz show up in your hair?',
    type: 'single',
    options: [
      { value: 'veryLittle', label: 'Very little' },
      { value: 'sometimes', label: 'Sometimes' },
      { value: 'often', label: 'Often' },
      { value: 'daily', label: 'Almost every day' },
    ],
  },
  {
    id: 'dryness',
    section: 'Concerns',
    title: 'How dry does your hair usually feel?',
    type: 'single',
    options: [
      { value: 'soft', label: 'Soft and moisturized' },
      { value: 'slightlyDry', label: 'Slightly dry' },
      { value: 'quiteDry', label: 'Quite dry' },
      { value: 'extremelyDry', label: 'Extremely dry' },
    ],
  },
  {
    id: 'damage',
    section: 'Condition',
    title: 'How healthy are your lengths and ends right now?',
    type: 'single',
    options: [
      { value: 'healthy', label: 'Healthy' },
      { value: 'slight', label: 'Slightly damaged' },
      { value: 'noticeable', label: 'Noticeably damaged' },
      { value: 'severe', label: 'Severely damaged' },
    ],
  },
  {
    id: 'breakage',
    section: 'Condition',
    title: 'How often do you get split ends or breakage?',
    helper: 'choose upto 3',
    type: 'multi',
    options: [
      { value: 'rarely', label: 'Rarely' },
      { value: 'occasionally', label: 'Occasionally' },
      { value: 'frequently', label: 'Frequently' },
      { value: 'veryFrequently', label: 'Very frequently' },
      { value: 'noIssues', label: 'No issues' },
    ],
  },
  {
    id: 'chemical',
    section: 'Lifestyle',
    title: 'Any chemical treatments in your hair lately?',
    type: 'single',
    options: [
      { value: 'none', label: 'No treatments' },
      { value: 'colour', label: 'Hair colour' },
      { value: 'smoothening', label: 'Smoothening / rebonding' },
      { value: 'bleach', label: 'Bleach / highlights' },
      { value: 'multiple', label: 'Multiple treatments' },

      {
        value: 'other',
        label: 'Other',
        allowText: true,
        placeholder: 'Mention your specific treatment',
      },
    ],
  },
  {
    id: 'heat',
    section: 'Lifestyle',
    title: 'How often do you reach for heat styling tools?',
    type: 'single',
    options: [
      { value: 'never', label: 'Never' },
      { value: 'rare', label: 'Less than once a week' },
      { value: 'weekly', label: '1–3 times a week' },
      { value: 'daily', label: 'Almost every day' },
    ],
  },
  {
    id: 'washing',
    section: 'Lifestyle',
    title: 'How often do you wash your hair?',
    type: 'single',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'twiceThrice', label: '2–3 times a week' },
      { value: 'weekly', label: 'Once a week' },
      { value: 'less', label: 'Less frequently' },
    ],
  },
  {
    id: 'primaryConcern',
    section: 'Goals',
    title: 'Which concern matters most to you right now?',
    helper: 'Choose up to 6',
    type: 'multi',
    options: [
      { value: 'hairFall', label: 'Hair fall' },
      { value: 'dandruff', label: 'Dandruff / scalp' },
      { value: 'dryness', label: 'Dryness' },
      { value: 'frizz', label: 'Frizz' },
      { value: 'damage', label: 'Damage / breakage' },
      { value: 'thinning', label: 'Thinning' },
      { value: 'dullness', label: 'Dullness' },
      { value: 'greying', label: 'Greying' },
    ],
  },
  {
    id: 'secondaryConcerns',
    section: 'Goals',
    title: 'What else should your routine keep an eye on?',
    helper: 'Choose up to 8',
    type: 'multi',
    maxSelect: 8,
    options: [
      { value: 'hairFall', label: 'Hair fall' },
      { value: 'thinning', label: 'Thinning' },
      { value: 'dandruff', label: 'Dandruff' },
      { value: 'oilyScalp', label: 'Oily scalp' },
      { value: 'dryScalp', label: 'Dry scalp' },
      { value: 'dryness', label: 'Dryness' },
      { value: 'frizz', label: 'Frizz' },
      { value: 'damage', label: 'Damage' },
      { value: 'breakage', label: 'Breakage' },
      { value: 'dullness', label: 'Dullness' },
      { value: 'weakness', label: 'Weak hair' },
      { value: 'greying', label: 'Greying' },
    ],
  },
  {
    id: 'outcome',
    section: 'Goals',
    title: 'What would make you happiest with a new routine?',
    type: 'single',
    options: [
      { value: 'strength', label: 'Stronger-looking hair' },
      { value: 'reducedFall', label: 'Reduced hair fall' },
      { value: 'healthyScalp', label: 'A healthier scalp' },
      { value: 'smoother', label: 'Smoother hair' },
      { value: 'moisture', label: 'Better moisture' },
      { value: 'lessFrizz', label: 'Less frizz' },
      { value: 'fuller', label: 'Fuller-looking hair' },
      { value: 'healthyLengths', label: 'Healthier lengths' },
    ],
  },
  {
    id: 'routinePref',
    section: 'Goals',
    title: 'How involved do you like your haircare to be?',
    type: 'single',
    options: [
      { value: 'simple', label: 'Simple and quick' },
      { value: 'balanced', label: 'Balanced' },
      { value: 'detailed', label: "I don't mind a detailed routine" },
    ],
  },
]